### ISSUE TITLE
Funds transfer 

### ISSUE THREAD

**Issue by sweetie77** [aurora-is-near/native-erc20-connector#25]
Help me, i transferred my  eth unds to another wallet, it didn't arrived 
![Screenshot_2022-11-01-16-57-28-11_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/37967183/199211090-1efae3ad-d3c2-4f21-8c6d-2c94a571a0a5.jpg)

**Comment by sept-en** [comment]
This repository is about a different scope. Please write to support@aurora.dev
